### ISSUE TITLE
Error trying to get request size using django middleware

### ISSUE THREAD

**Issue by kevyder** [apitally/python-client#14]
Hi guys, english isn't my first language, so please excuse any mistakes.

I'm trying to use the last version of django middleware (0.6.1) i have the next error:

**invalid literal for int() with base 10: ''**
Request Method:	GET
Request URL:	http://localhost:8001/api/job/
Django Version:	5.0.3
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: ''
Exception Location:	/usr/local/lib/python3.10/site-packages/apitally/client/base.py, line 135, in add_request
Raised during:	job.views.JobList
Python Executable:	/usr/local/bin/python
Python Version:	3.10.13
Python Path:	
['/app',
 '/usr/local/lib/python310.zip',
 '/usr/local/lib/python3.10',
 '/usr/local/lib/python3.10/lib-dynload',
 '/usr/local/lib/python3.10/site-packages']

It looks like that when you are trying to get the size of a request ( `request.headers.get("Content-Length")`) and the result is '' (an empty string) it impossible to make the convertion to an integer object in line 135 of **/apitally/client/base.py** file and there is not validation for an empty string in line 134 of **/apitally/client/base.py** file.

Right now, the only option i have is using the 0.3.4 of the library.

**Comment by itssimon** [comment]
Thanks for reporting this! I will push a fix shortly.

Do you use the `django.middleware.common.CommonMiddleware` in your application? If not, you may want to add it after the `ApitallyMiddleware` as that is where the `Content-Length` header is being set in Django.

**Comment by itssimon** [comment]
This is now fixed in the latest version v0.6.2.

**Comment by kevyder** [comment]
Hi, yes, i was using `django.middleware.common.CommonMiddleware` but i changed the library version to the last one (v0.6.2) and it looks like everything is working fine, thank you for the fix.
